### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by photon1503**
See https://github.com/andreasdahl1987/DahlDesignProperties/issues/15

* In order to compile locally, please execute requirements.cmd which will copy all necessary DLLs to a common subfolder (excluded in Git).
* Removed relative paths from csproj
* Added vscode build task 
* Cleaned up main program DataPluginDemo.cs
* Moved DDC properties to Sections\DDC
* Moved Dashboard properties to Sections\Dashboard
* Moved all iRacing related stuff to iRacing folder
* Car settings are in iRacing\CarInfos
* Track settings are in iRacing\TrackInfos

### CODE REVIEW

**Comment by andreasdahl1987** [comment]
@photon1503 
image
Getting a lot or errors. Suggestions?

**Comment by photon1503** [comment]
@andreasdahl1987 did you run requirements.cmd?
This one will copy all DLLs to a new subfolder "DLLs" and all references should be fine.

But to be honest, I didn't yet check it in VS - only VS Code

**Comment by photon1503** [comment]
VS also works here, can also build the solution. The project folder should look like this
image

**Comment by andreasdahl1987** [comment]
Yes, that worked. Tested, there is way to much stuff to test - but I've tested the main elements with replays and some sessions, all seems to work just like before. Great!

**Comment by andreasdahl1987** [comment]
Some of the files/folders in the repo is not showing up in my project in VS2022. Any idea why this might be?

**Comment by andreasdahl1987** [comment]
This also fixes #15 , not sure how to make this merge record that :S

**Comment by photon1503** [comment]
> Some of the files/folders in the repo is not showing up in my project in VS2022. Any idea why this might be?

@andreasdahl1987 didn't have all the files included in the Solution, that's the reason why they are hidden in VS. Already changed this for the cmd file

**Comment by andreasdahl1987** [comment]
@photon1503 Ah, makes sense.  It is https://github.com/andreasdahl1987/DahlDesignProperties/blob/master/DahlDesign.Plugin.csproj where this is described, yeah? Not possible to make commits to this PR after it has been merged, right? You'll have to make a new PR?

**Comment by photon1503** [comment]
> @photon1503 Ah, makes sense. It is https://github.com/andreasdahl1987/DahlDesignProperties/blob/master/DahlDesign.Plugin.csproj where this is described, yeah? Not possible to make commits to this PR after it has been merged, right? You'll have to make a new PR?

@andreasdahl1987 exactly - did this yesterday but obviously in the wrong repository :-)

**Pull request merged**
