### PR TITLE
Add BMW LMDh

### PR DESCRIPTION
**Pull request by Jarne-T**
Added support for the BMW LMDh and added an IsHybrid property to the Cars model

### CODE REVIEW

**Comment by andreasdahl1987** [comment]
Thanks man :) I'll have a chance to try this out in the weekend! The dash as well naturally

**Comment by andreasdahl1987** [comment]
Here did you find the optimal shift point values btw? I had a look and I found a power curve showing maximum output at 95% of max engine speed (8200 rpm max), which translates to 7790 rpm.

**Comment by Jarne-T** [comment]
I used the [iRacing manual](https://s100.iracing.com/wp-content/uploads/2023/10/BMW-M-Hybrid-V8.pdf). At the bottom of page 6 it explains the optimal shift point is when all LEDs are illuminated but not flashing red. The manual says this is at 7100 rpm, but I think that's a typo because that's obviously way to early. I tested it in iRacing and found that at 7700 rpm all LEDs are on and above 7900 rpm they all flash red.

**Comment by andreasdahl1987** [comment]
Ok, I'll look into it a bit more. The way the optimal shift point stuff works for my plugin is a bit different from most other LED profiles as such. The number I want in carInfo is the actual RPM where the gear change should happen, not adjusted for reaction time, which RPM lights usually are. My plugin does the calculations regarding how much earlier to show the shift light in order to hit the correct RPM perfectly. It takes into consideration your thottle application, which gear you are in, if DRS is open, hybrid power is being used, etc. One user is also working on an algorithm to adjust this if going uphill/downhill. I know for these modern cars it doesnt really matter all that much, but hey, lets optimize what we can :D If you look at the property `ShiftLightRPM` while driving, you'll see it is constantly adjusting

**Comment by Jarne-T** [comment]
I didn't know that. What would be the best way to find out the optimal shift point/rpm to use in the plugin?

**Comment by andreasdahl1987** [comment]
For many cars it is easy, they are power capped with an RPM limiter. Higher horse power the higher RPM. Such as indy cars for instance. For some cars I have found forum threads where people have been doing analytics on gear changes and acceleration, and when I cant find anything I have been using telemetry from really good laptimes from VRS to see what RPM the "pros" reach before shifting

**Comment by andreasdahl1987** [comment]
Just found a replay for a WR le mans lap, he was shifting consistently around 7850-7880, so I think that must work

**Comment by andreasdahl1987** [comment]
Did some adjustments, Might also have to look over the pit stop times, mine was off by a few seconds. Havent had a chance to test dual clutch launch since I cant seem to be able to deactivate the TC? I've set a button to it but nothing happens :S

**Comment by Jarne-T** [comment]
I just tested again and it seems like I can not turn off TC either. Maybe they did something with the recent update because I'm quite sure I could toggle it a week ago. I did find that TC doesn't really interfere with a launch because the wheelspin is very minimal in this car but nonetheless the option is there so it should work.

**Pull request merged**
